baseURL = "https://panchengwu.top"
languageCode = "en-us"
title = "Pancheng Wu | 吴盼成"
theme = "hugo-theme-yinyang"
DefaultContentLanguage = "cn"

[author]
  name = "Pancheng Wu"
  homepage = "https://panchengwu.top"

[languages]
  [languages.en]
    contentDir = "content/en"
    languageName = "English"
    weight = 1
  [languages.cn]
    contentDir = "content/cn"
    languageName = "Chinese"
    weight = 1

[params]
mainSections = ["posts"]

[[params.socials]]
name = "Github"
link = "https://github.com/01print/"

[[params.socials]]
name = "About"
link = "https://panchengwu.top"
